[settings]
# COMPOSITE SETTINGS
composite = true 
nnew = 1024 
ntotal = 722 
numprocs = 30
time_step = 1000
bg_file = /home/c4052420/spectra_analysis_pipeline/data/2MS_50_90.dat
vzc_file = /home/c4052420/spectra_analysis_pipeline/data/vzcr-rad-2ms5000-5000-44000et.dat
data_dir = /home/c4052420/spectra_analysis_pipeline/data/
breaks = [0.05, 0.0661, 0.125, 0.148, 0.27]
rps = [100, 100, 100, 100, 140, 140]
smoothingparams = [10, 10, 10, 50, 50, 20]
peakpars = [0.75, 45, 200, 8]



#MCMC SETTINGS
n_peaks = 15
n_draws = 2
n_tune= 2
results_dir = /home/c4052420/spectra_analysis_pipeline/results/
run_title = stitched 